const $=id=>document.getElementById(id);
const screens={home:$("home"),booth:$("booth"),preview:$("preview"),admin:$("admin")};
const video=$("video"), stripCanvas=$("stripCanvas"), stripCtx=stripCanvas.getContext("2d"), previewCanvas=$("previewCanvas"), previewCtx=previewCanvas.getContext("2d");
stripCanvas.width=600;stripCanvas.height=1800;previewCanvas.width=600;previewCanvas.height=1800;
let stream=null,photos=[],backgroundImage=null,autoReturnTimer=null;
const defaults={appColor:"#D2E4E5",stripColor:"#D2E4E5",photoCount:3,countdown:3,defaultCopies:1,autoReturnSeconds:20,adminPin:"1234",autoSave:true,autoPrint:false,topText:"ALOHA!",bottomText:"Thanks for celebrating with us!",stats:{sessions:0,prints:0,shares:0}};
let settings=structuredClone(defaults);
function showScreen(name){clearTimeout(autoReturnTimer);Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active")}
function saveSettings(){localStorage.setItem("alohaPhotoboothSettingsV3",JSON.stringify(settings))}
function loadSettings(){const saved=localStorage.getItem("alohaPhotoboothSettingsV3");if(saved){settings={...structuredClone(defaults),...JSON.parse(saved)};settings.stats={...defaults.stats,...(settings.stats||{})}}const bg=localStorage.getItem("alohaPhotoboothBackgroundV3");if(bg){backgroundImage=new Image();backgroundImage.onload=drawStrip;backgroundImage.src=bg}updateAdmin();drawStrip()}
function updateAdmin(){document.documentElement.style.setProperty("--app",settings.appColor);$("settingAppColor").value=settings.appColor;$("settingStripColor").value=settings.stripColor;$("settingPhotoCount").value=settings.photoCount;$("settingCountdown").value=settings.countdown;$("settingCopies").value=settings.defaultCopies;$("settingReturn").value=settings.autoReturnSeconds;$("settingPin").value=settings.adminPin;$("settingAutoSave").checked=settings.autoSave;$("settingAutoPrint").checked=settings.autoPrint;$("topText").value=settings.topText;$("bottomText").value=settings.bottomText;updateStats()}
function readAdmin(){settings.appColor=$("settingAppColor").value||"#D2E4E5";settings.stripColor=$("settingStripColor").value||"#D2E4E5";settings.photoCount=clamp(Number($("settingPhotoCount").value),1,6);settings.countdown=clamp(Number($("settingCountdown").value),1,10);settings.defaultCopies=clamp(Number($("settingCopies").value),1,20);settings.autoReturnSeconds=clamp(Number($("settingReturn").value),5,120);settings.adminPin=$("settingPin").value||"1234";settings.autoSave=$("settingAutoSave").checked;settings.autoPrint=$("settingAutoPrint").checked;settings.topText=$("topText").value||"ALOHA!";settings.bottomText=$("bottomText").value||""}
function clamp(v,min,max){if(Number.isNaN(v))return min;return Math.max(min,Math.min(max,v))}
function getPhotoBoxes(){const count=clamp(Number(settings.photoCount),1,6),padding=36,top=130,bottom=120,gap=28,availableH=1800-top-bottom-padding,h=(availableH-gap*(count-1))/count,w=600-padding*2;return Array.from({length:count},(_,i)=>({x:padding,y:top+i*(h+gap),w,h}))}
function drawStrip(){stripCtx.clearRect(0,0,600,1800);stripCtx.fillStyle=settings.stripColor;stripCtx.fillRect(0,0,600,1800);if(backgroundImage)stripCtx.drawImage(backgroundImage,0,0,600,1800);stripCtx.textAlign="center";stripCtx.fillStyle="#222";stripCtx.font="bold 38px Arial";stripCtx.fillText(settings.topText,300,72);getPhotoBoxes().forEach((box,i)=>{stripCtx.fillStyle="white";roundRect(stripCtx,box.x-8,box.y-8,box.w+16,box.h+16,18,true);if(photos[i])drawCroppedImage(stripCtx,photos[i],box.x,box.y,box.w,box.h);else{stripCtx.fillStyle="rgba(255,255,255,.72)";roundRect(stripCtx,box.x,box.y,box.w,box.h,14,true);stripCtx.fillStyle="#777";stripCtx.font="24px Arial";stripCtx.fillText(`Photo ${i+1}`,box.x+box.w/2,box.y+box.h/2)}});stripCtx.fillStyle="#222";stripCtx.font="24px Arial";stripCtx.fillText(settings.bottomText,300,1742);previewCtx.clearRect(0,0,600,1800);previewCtx.drawImage(stripCanvas,0,0,600,1800)}
function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();if(fill)ctx.fill()}
function drawCroppedImage(ctx,img,x,y,w,h){const ir=img.width/img.height,tr=w/h;let sx,sy,sw,sh;if(ir>tr){sh=img.height;sw=img.height*tr;sx=(img.width-sw)/2;sy=0}else{sw=img.width;sh=img.width/tr;sx=0;sy=(img.height-sh)/2}ctx.save();roundRect(ctx,x,y,w,h,14,false);ctx.clip();ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);ctx.restore()}
async function startCamera(){$("cameraMessage").textContent="Starting camera...";$("cameraMessage").classList.remove("hidden");if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){$("cameraMessage").textContent="Camera access is not available. Open from Safari using your HTTPS GitHub Pages link.";throw new Error("getUserMedia unavailable")}if(stream){video.srcObject=stream;await video.play();$("cameraMessage").classList.add("hidden");return}try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:"user"}});video.srcObject=stream;video.setAttribute("playsinline","");video.muted=true;await new Promise(resolve=>{if(video.readyState>=2)resolve();else video.onloadedmetadata=resolve});await video.play();$("cameraMessage").classList.add("hidden");$("statusText").textContent="Camera Ready"}catch(error){$("cameraMessage").textContent="Camera is blocked or unavailable. In Safari, allow camera access for this site, then reload.";$("statusText").textContent="Camera Blocked";throw error}}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function runCountdown(seconds){for(let i=seconds;i>0;i--){$("countdown").textContent=i;await wait(1000)}$("countdown").textContent="📸";$("flash").classList.add("on");await wait(350);$("countdown").textContent="";$("flash").classList.remove("on")}
function capturePhoto(){const temp=document.createElement("canvas");temp.width=video.videoWidth||1280;temp.height=video.videoHeight||720;const ctx=temp.getContext("2d");ctx.translate(temp.width,0);ctx.scale(-1,1);ctx.drawImage(video,0,0,temp.width,temp.height);const img=new Image();img.src=temp.toDataURL("image/png");return img}
async function takePhotos(){try{readAdmin();saveSettings();await startCamera();photos=[];drawStrip();const count=clamp(Number(settings.photoCount),1,6);for(let i=0;i<count;i++){$("statusText").textContent=`Photo ${i+1} of ${count}`;await runCountdown(settings.countdown);const photo=capturePhoto();await new Promise(resolve=>photo.onload=resolve);photos.push(photo);drawStrip();await wait(450)}settings.stats.sessions+=1;saveSettings();updateStats();drawStrip();if(settings.autoSave)saveStrip(false);showScreen("preview");if(settings.autoPrint)setTimeout(()=>printStrip(true),700);autoReturnTimer=setTimeout(returnHome,settings.autoReturnSeconds*1000)}catch(error){console.error(error);alert("Camera did not start. Make sure you are using Safari with the HTTPS GitHub Pages link and camera permission is allowed.")}}
function saveStrip(showAlert=true){const a=document.createElement("a");a.download=`aloha-photobooth-${Date.now()}.png`;a.href=stripCanvas.toDataURL("image/png");a.click();if(showAlert)alert("Photo strip saved.")}
function printStrip(auto=false){const copies=auto?settings.defaultCopies:clamp(Number(prompt("How many strips would you like to print?",String(settings.defaultCopies))),1,20);if(!copies)return;settings.stats.prints+=copies;saveSettings();updateStats();const data=stripCanvas.toDataURL("image/png");const win=window.open("","_blank");win.document.write(`<html><head><title>Print</title><style>body{margin:0;padding:.25in;background:white}.sheet{display:flex;flex-wrap:wrap;gap:.15in;justify-content:center}img{width:2in;height:6in;object-fit:contain;page-break-inside:avoid}</style></head><body><div class="sheet">${Array.from({length:copies},()=>`<img src="${data}">`).join("")}</div><script>window.onload=()=>{window.focus();window.print();}<\/script></body></html>`);win.document.close()}
function canvasToBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,"image/png"))}
async function shareStrip(){try{const blob=await canvasToBlob(stripCanvas);const file=new File([blob],"aloha-photobooth.png",{type:"image/png"});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:"ALOHA!",text:"Here is your photo strip!"});settings.stats.shares+=1;saveSettings();updateStats()}else{saveStrip(false);alert("AirDrop/Share is not available here, so the strip was saved.")}}catch(error){console.error(error)}}
function returnHome(){photos=[];drawStrip();showScreen("home")}
function updateStats(){$("statSessions").textContent=settings.stats.sessions||0;$("statPrints").textContent=settings.stats.prints||0;$("statShares").textContent=settings.stats.shares||0}
function uploadImage(input,callback){const file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=event=>callback(event.target.result);reader.readAsDataURL(file)}
$("startBtn").addEventListener("click",async()=>{showScreen("booth");try{await startCamera()}catch(error){console.error(error)}});
$("captureBtn").addEventListener("click",takePhotos);$("homeBtn").addEventListener("click",returnHome);$("previewHomeBtn").addEventListener("click",returnHome);$("doneBtn").addEventListener("click",returnHome);$("retakeBtn").addEventListener("click",()=>showScreen("booth"));
$("printBtn").addEventListener("click",()=>printStrip(false));$("printFromBoothBtn").addEventListener("click",()=>printStrip(false));$("saveBtn").addEventListener("click",()=>saveStrip(true));$("saveFromBoothBtn").addEventListener("click",()=>saveStrip(true));$("shareBtn").addEventListener("click",shareStrip);$("shareFromBoothBtn").addEventListener("click",shareStrip);
function openAdmin(){const pin=prompt("Enter admin PIN:");if(pin===settings.adminPin)showScreen("admin");else if(pin!==null)alert("Incorrect PIN.")}
$("adminBtn").addEventListener("click",openAdmin);$("adminBtn2").addEventListener("click",openAdmin);$("closeAdminBtn").addEventListener("click",()=>showScreen("home"));
$("saveSettingsBtn").addEventListener("click",()=>{readAdmin();saveSettings();updateAdmin();drawStrip();alert("Settings saved.")});
$("resetStatsBtn").addEventListener("click",()=>{settings.stats={sessions:0,prints:0,shares:0};saveSettings();updateStats()});
$("resetTemplateBtn").addEventListener("click",()=>{if(!confirm("Reset uploaded template?"))return;localStorage.removeItem("alohaPhotoboothBackgroundV3");backgroundImage=null;drawStrip()});
$("templateUpload").addEventListener("change",event=>{uploadImage(event.target,src=>{localStorage.setItem("alohaPhotoboothBackgroundV3",src);backgroundImage=new Image();backgroundImage.onload=drawStrip;backgroundImage.src=src})});
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"))}
loadSettings();showScreen("home");
